"use client";

import { createContext, useContext, type ReactNode } from "react";
import type { ActivityId, Advisor, Candidate, EndingDefinition, EventNode, EventChoice, ExperimentDefinition, LabMember, ProjectDefinition, ResearchProgram } from "./types";

export type Locale = "zh-CN" | "en-US";

const LocaleContext = createContext<{locale:Locale;setLocale:(locale:Locale)=>void}>({locale:"zh-CN",setLocale:()=>undefined});

export function LocaleProvider({locale,setLocale,children}:{locale:Locale;setLocale:(locale:Locale)=>void;children:ReactNode}) {
  return <LocaleContext.Provider value={{locale,setLocale}}>{children}</LocaleContext.Provider>;
}

export function useLocale() {
  const value=useContext(LocaleContext);
  return {...value,t:(zh:string,en:string)=>value.locale==="en-US"?en:zh};
}

export function LanguageToggle({compact=false}:{compact?:boolean}) {
  const {locale,setLocale}=useLocale();
  return <div className={`language-toggle${compact?" compact":""}`} aria-label="Language / 语言">
    <button className={locale==="zh-CN"?"active":""} onClick={()=>setLocale("zh-CN")} aria-pressed={locale==="zh-CN"}>中文</button>
    <button className={locale==="en-US"?"active":""} onClick={()=>setLocale("en-US")} aria-pressed={locale==="en-US"}>EN</button>
  </div>;
}

const CANDIDATE_EN:Record<string,[string,string,string,string,string,string,string]> = {
  "lin-xiaoman":["Lin Xiaoman","Pharmacy honors student","A pipette feels like an extra hand, but opening R still feels terrifying.","Steady Hands","Wet-lab success +8%","Code Anxiety","Omics analysis takes longer"],
  "zhou-yiming":["Zhou Yiming","Mathematics graduate changing fields","Believes every problem deserves a plot before an answer.","Data Instinct","Negative data more readily becomes a figure","Lab Novice","Starts with lower technique proficiency"],
  "chen-ruoshui":["Chen Ruoshui","Raised in a TCM family","Knows classical formulas by heart and still demands modern evidence.","Herbal Radar","TCM project novelty +6","Overextended Scope","Parallel projects add extra pressure"],
  "gao-fei":["Gao Fei","Experienced undergraduate researcher","Never misses an animal study, always starts writing tomorrow.","Animal Whisperer","Animal-study success +10%","Procrastinator","Lower writing gains in the first two years"],
  "tang-keke":["Tang Keke","Clinical pharmacy background","Knows which questions matter—and that charts do not become mechanisms by themselves.","Clinical Sense","Better match with translational journals","Shift Conflicts","May occasionally lose a time slot"],
  "li-siyuan":["Li Siyuan","General-entry graduate student","An ordinary start, but the best failure records in the lab.","Resilient","Failures accelerate later learning","Self-Doubt","Technical failures cost extra SAN"],
  "shen-xingchi":["Shen Xingchi","No prior lab experience","Took ten minutes to put on gloves the first time, then learned unusually fast.","Fast Learner","Proficiency growth +50%","Rookie Accidents","First attempts contaminate more easily"],
  "lu-jiuyue":["Lu Jiuyue","Former lab technician","Can repair a centrifuge and convince everyone to go home at midnight.","Equipment Savvy","Instrument-based success +7%","Cannot Say No","Social favors create more debt"],
  "chen-mo":["Chen Mo","Bioinformatics graduate","Quiet, precise, and every script is documented.","Reproducible","Integrity and replication evidence gain more value","Socially Anxious","Asking for help is less effective"],
  "fang-tang":["Fang Tang","Student research organizer","Knows everyone in the institute; the notebook is usually in a meeting room.","Resource Network","Cheaper collaboration and easier grant applications","Meeting Magnet","More administrative interruptions"],
  "qiao-mu":["Qiao Mu","Environmental science crossover","Obsessed with pollutants, indifferent to sleep.","Night Owl","Reduced overtime energy penalty","Caffeine Dependence","Repeated overtime drains more SAN"],
  "xu-zhizhi":["Xu Zhizhi","Published Chinese-core first author","Writes papers like stories and runs experiments like mysteries.","Writing Machine","Paper and reviewer-response gains +40%","Unsteady Hands","Precision experiments −8%"],
};

export function candidateText(candidate:Candidate,locale:Locale) {
  if(locale==="zh-CN")return candidate;
  const row=CANDIDATE_EN[candidate.id];if(!row)return candidate;
  return {...candidate,name:row[0],background:row[1],bio:row[2],trait:row[3],traitEffect:row[4],flaw:row[5],flawEffect:row[6],tags:candidate.tags.map(tag=>freeText(tag,locale,"Research"))};
}

const ADVISOR_EN:Record<string,[string,string,string,string,string,string,string]> = {
  "lu-wenshan":["Lu Wenshan","Professor · Lab PI","Doctoral supervisor","Provincial Research Leader","Strict","Data Purist","Show me the raw data first. The story can wait."],
  "xu-jingzhi":["Xu Jingzhi","Associate Professor · Young PI","Master's supervisor","Early-Career Fellow","Very strict","High-Pressure PI","This direction has promise, so weekends must have promise too."],
  "chen-an":["Chen An","Professor · Center Director","Doctoral supervisor","Discipline Chair","Relaxed","Hands-Off","Choose your own direction. Bring me a closed evidence loop by graduation."],
  "wen-yuqing":["Wen Yuqing","Research Professor · Deputy Director","Doctoral supervisor","National Young Scholar","Supportive","Caring Mentor","Rest first. The data will still be here tomorrow."],
  "jin-shouxin":["Jin Shouxin","Professor · Budget Signatory","Doctoral supervisor","Distinguished Professor","Strict","Budget Miser","Why can this box of tips not be stretched a little further?"],
  "fu-yuan":["Fu Yuan","Key Laboratory PI","Doctoral supervisor","National Distinguished Scholar","Moderate","Well Funded","If the design is sound, buy it. Bad reagents waste more money."],
  "gao-yin":["Gao Yin","Professor · Journal Editor","Doctoral supervisor","Teaching Fellow","Very strict","Publication Driven","More experiments are not always better. The paper must be publishable."],
  "he-linchuan":["He Linchuan","Chief Physician · Joint Professor","Doctoral supervisor","Clinical Program Leader","Moderate","Clinical Connector","I can coordinate samples, but the question must matter to patients."],
  "ning-shuang":["Ning Shuang","Independent Early-Career PI","Master's supervisor","Overseas Young Scholar","Attentive","Hands-On Mentor","I will run the first gel with you. You teach the next one."],
};

export function advisorText(advisor:Advisor,locale:Locale) {
  if(locale==="zh-CN")return advisor;const row=ADVISOR_EN[advisor.id];if(!row)return advisor;
  return {...advisor,name:row[0],title:row[1],supervision:row[2] as Advisor["supervision"],honor:row[3],strictness:row[4],archetype:row[5],quote:row[6],eventBias:"Research management"};
}

const NPC_NAMES=["Han Zhe","Su Qing","Shao Yu","Jiang Nan","Luo Xin","Bai Lu","Zhao Qi","Lin Zhou","Wu Tong","Ye Jia","Sun Ning","Qiu Ran","Mo Li","Yuan Ye","Fang Qin","Cheng Yu","Gu Yan","Tian Miao","An Qi","Xie Chuan"];
const NPC_ROLE:Record<string,string>={"博三":"PhD Year 3","博四":"PhD Year 4","硕二":"MSc Year 2","博二":"PhD Year 2","科研助理":"Research Assistant","硕一":"MSc Year 1","博士后":"Postdoc","仪器管理员":"Core Manager","博士生":"PhD Student","硕三":"MSc Year 3","临床研究生":"Clinical Graduate","博一":"PhD Year 1","科研秘书":"Research Administrator","博五":"PhD Year 5","实验师":"Lab Specialist","联培生":"Visiting Student"};
const NPC_SKILL=["Western blot optimization","Statistics and R","Cell culture","Animal models","Flow cytometry","Histopathology","Transcriptomics","LC–MS/MS","Metabolomics","Scientific writing","Clinical samples","Microbiome","TCM pharmacology","Organoids","Reimbursement and ethics","Immunofluorescence","Project design","PCR/qPCR","Biosafety","Proteomics"];
const NPC_PERSONALITY=["Tough outside, kind inside","Calm and dependable","Well informed","Principled","Efficiency first","Meticulous and reserved","Ambitious","By the book","Active at night","Perfectionist","Warm and talkative","Curious","Gentle but firm","Risk taker","Never forgets paperwork","Highly social","Graduation countdown","Careful and nervous","Rigorous and direct","Easygoing"];
export function memberText(member:LabMember,locale:Locale,index=0){return locale==="zh-CN"?member:{...member,name:NPC_NAMES[index]??member.name,role:NPC_ROLE[member.role]??"Lab Member",specialty:NPC_SKILL[index]??"Research support",personality:NPC_PERSONALITY[index]??"Colleague"};}

const PROGRAM_EN:Record<string,[string,string,string]>={
  "tox-dili":["Toxicology","Drug-Induced Liver and Kidney Injury","From exposure and organ phenotypes to metabolism and cell-death mechanisms."],
  "tox-multiorgan":["Toxicology","Multi-Organ Toxicity","Compare tissue-specific drug injury across heart, lung, nervous system, and kidney."],
  "pharm-metabolic":["Pharmacology","Metabolic Pharmacology","Trace how defined drugs reshape cross-organ metabolic signaling."],
  "pharm-resistance":["Pharmacology","Cancer Drug Resistance","Dissect resistance with cells, organoids, and rescue experiments."],
  "tcm-processing":["Traditional Chinese Medicine","Toxic Herbs and Processing","Connect toxic constituents, processing chemistry, and mechanism."],
  "tcm-formula":["Traditional Chinese Medicine","Herb Pairing and Formulas","Study how component interactions alter exposure, efficacy, and toxicity."],
  "natural-protection":["Natural Products","Organ Protection","Test defined natural compounds in classical organ-injury models."],
  "natural-mechanism":["Natural Products","Pharmacological Mechanisms","Explain natural-product activity through metabolism, inflammation, immunity, and ferroptosis."],
  "env-emerging":["Environment & Food","Emerging Pollutants","Focus on PFAS, microplastics, bisphenol substitutes, and combined exposure."],
  "food-toxicants":["Environment & Food","Foodborne Toxicants","Study mycotoxins, heat-generated contaminants, and DNA damage."],
  "biotech-human-model":["Biotechnology","Human-Relevant Models","Compare 2D, organoid, and multi-organ systems for predictive toxicology."],
  "biotech-therapy-safety":["Biotechnology","Advanced-Therapy Safety","Evaluate risks from AAV, mRNA-LNP, gene editing, and CAR-T."],
};
export function programText(program:ResearchProgram,locale:Locale){if(locale==="zh-CN")return program;const row=PROGRAM_EN[program.id];return row?{...program,domain:row[0],name:row[1],summary:row[2]}:program;}

const PROJECT_TITLES_EN=[
  "APAP–CYP2E1/GSH ferroptosis and schisandrin B intervention","Isoniazid/rifampicin co-exposure, bile-acid homeostasis, and liver injury","Diclofenac reactive metabolites and immune-mediated liver injury","Cisplatin–OCT2 tubular injury and cimetidine blockade","Gentamicin-induced lysosomal stress in proximal tubules",
  "Doxorubicin–mtDNA/ALAS1 cardiac ferroptosis and 5-ALA rescue","Bleomycin-induced alveolar ferroptosis and pulmonary fibrosis","Paclitaxel-driven dorsal-root inflammation and peripheral neuropathy","Valproate neurodevelopmental toxicity and HDAC inhibition in zebrafish","Tenofovir OAT1/OAT3-mediated nephron-segment toxicity",
  "Metformin remodeling of multi-organ glucose control","Semaglutide control of gut–islet–liver nutrient sensing","Empagliflozin suppression of NLRP3 in diabetic kidney disease","Pioglitazone–PPARγ control of MASH lipotoxicity","Fenofibrate–PPARα improvement of hepatic lipid deposition",
  "Osimertinib resistance through the ANGPTL4/NDRG1 extracellular matrix axis","Dauricine plus osimertinib induces SAT1-dependent ferroptosis","Sorafenib resistance through the SLC7A11/GPX4 ferroptosis axis","Homologous-recombination recovery in olaparib-resistant ovarian organoids","Paclitaxel resistance through ABCB1 and lysosomal sequestration",
  "Ferroptosis differences between raw and processed Polygonum multiflorum","Origin-dependent TSG/anthraquinone profiles and Polygonum multiflorum hepatotoxicity","Processing-dependent changes in Aconitum diester alkaloids and cardiotoxicity","Triptolide-induced hepatocyte ferroptosis through NRF2 degradation","Aristolochic acid I DNA adducts and mutational Signature 22",
  "Aconitum–licorice compatibility reduces diester-alkaloid cardiotoxicity","Three Gegen Qinlian Decoction constituents protect the ETEC-injured intestinal barrier","Huanglian Jiedu Decoction alters geniposide pharmacokinetics","Ephedra–licorice compatibility changes cardiovascular ephedrine exposure","Baicalin/berberine co-precipitation and absorption in Scutellaria–Coptis pairing",
  "Schisandrin B alleviates APAP-induced hepatocyte ferroptosis","Quercetin alleviates cisplatin proximal-tubule injury","Curcumin mitigates doxorubicin cardiac oxidative injury","Resveratrol intervention in bleomycin-induced pulmonary fibrosis","Sulforaphane suppresses aflatoxin B1 hepatocyte injury",
  "Berberine activates AMPK to improve fatty liver","Baicalin suppresses ETEC-induced intestinal-barrier inflammation","Tanshinone IIA regulates endothelial oxidative stress","Ginsenoside Rg3 regulates tumor vessels and the immune microenvironment","Artemisinin derivatives induce ferroptosis in resistant tumor cells",
  "Maternal–fetal liver transcriptional responses to PFOA versus GenX","Interaction of PFOS and high-fat diet in hepatic lipid deposition","Polystyrene microplastics plus BPA worsen diabetic intestinal injury","Polyethylene microplastics plus TBBPA disrupt the gut microbiome","BPA versus BHPF alters intestinal-organoid differentiation trajectories",
  "Aflatoxin B1 DNA-adduct formation in liver organoids","DON inhibition of intestinal-organoid renewal","Cellular heterogeneity after combined DON and zearalenone exposure","Acrylamide neurodevelopmental toxicity through NLRP3 pyroptosis","PhIP metabolic activation and DNA damage in colon organoids",
  "Single-cell comparison of APAP responses in 2D cells and 3D liver microtissues","ATP/ADP-sensing kidney-organoid model of cisplatin toxicity","Multicellular human cardiac-microtissue model of doxorubicin injury","Multi-organ organoid differences in AFB1/AAI/PhIP metabolism","Six-tissue microphysiological comparison of metformin and semaglutide",
  "High-dose AAV9 toxicity in liver and dorsal-root ganglia","Anti-PEG responses and tissue distribution after repeat mRNA-LNP dosing","Influence of individual SNVs on Cas9 off-target formation","Structural-variation and aneuploidy risks from base editors","Single-cell mechanism of breakthrough cytokine-release syndrome after CAR-T",
];

const SCI_REPLACEMENTS:Array<[RegExp,string]>=[
  [/人源/g,"human "],[/小鼠/g,"mouse"],[/大鼠/g,"rat"],[/斑马鱼胚胎/g,"zebrafish embryos"],[/斑马鱼/g,"zebrafish"],[/类器官/g,"organoid"],[/肝细胞/g,"hepatocytes"],[/肾小管细胞/g,"renal tubular cells"],[/心肌细胞/g,"cardiomyocytes"],[/肠上皮细胞/g,"intestinal epithelial cells"],[/肿瘤细胞/g,"tumor cells"],[/细胞/g,"cells"],[/肝损伤/g,"liver injury"],[/肾损伤/g,"kidney injury"],[/肺纤维化/g,"pulmonary fibrosis"],[/高脂饮食/g,"high-fat diet"],[/铁死亡/g,"ferroptosis"],[/氧化应激/g,"oxidative stress"],[/炎症/g,"inflammation"],[/脂质代谢/g,"lipid metabolism"],[/能量代谢/g,"energy metabolism"],[/细胞分化/g,"cell differentiation"],[/紧密连接/g,"tight junction"],[/菌群/g,"microbiome"],[/动物/g,"animal"],[/病理/g,"histopathology"],[/分子/g,"molecular validation"],[/机制/g,"mechanism"],[/转录组/g,"transcriptomics"],[/代谢组/g,"metabolomics"],[/蛋白组/g,"proteomics"],[/单细胞/g,"single-cell"],[/质谱/g,"mass spectrometry"],[/遗传毒性/g,"genotoxicity"],[/挽救/g,"rescue"],[/验证/g,"validation"],[/比较/g,"comparison"],[/与/g," and "],[/、/g,", "],[/—/g," → "],[/-/g,"–"]
];
function scienceText(value:string,fallback:string){let result=value;for(const [pattern,replacement] of SCI_REPLACEMENTS)result=result.replace(pattern,replacement);return /[\u3400-\u9fff]/.test(result)?fallback:result.replace(/\s+/g," ").trim();}

export function projectText(project:ProjectDefinition,locale:Locale){
  if(locale==="zh-CN")return project;const title=PROJECT_TITLES_EN[Number(project.id.replace("project-",""))-1]??"Mechanistic research project";
  return {...project,title,domain:PROGRAM_EN[project.programId]?.[0]??"Biomedical Science",intervention:scienceText(project.intervention,"Defined compounds named in the project title"),model:scienceText(project.model,"Disease-relevant cell, animal, or organoid model"),target:scienceText(project.target,"Specified molecular mechanism"),mechanismAxis:scienceText(project.mechanismAxis,"Specified molecular mechanism"),route:scienceText(project.route,"Phenotype → validation → mechanism"),question:`Can ${title.charAt(0).toLowerCase()+title.slice(1)} produce a reproducible and experimentally actionable effect?`,knowledgeGap:"Current evidence still lacks a complete dose–time relationship, intervention at a key node, and cross-model validation."};
}

const EXPERIMENT_EN:Record<string,[string,string,string,string,string]>={
  "cell-study":["Run Cell Study","Cell Study","Establish treatment groups, dose, and timing to generate samples and an initial phenotype.","Cell platform","Cell line or primary cells"],"cell-toxicity":["Cell Viability Assay","Cell Viability","Measure survival and injury using CCK-8, MTT, or LDH.","Plate reader","Cells"],"ros":["ROS / Oxidative Stress","ROS","Measure reactive oxygen species and antioxidant capacity.","Fluorescence reader","Cells or tissue"],"apoptosis":["Apoptosis / TUNEL","Apoptosis","Distinguish apoptosis, necrosis, and related death programs.","Imaging system","Cells or sections"],"flow":["Flow Cytometry","Flow","Quantify cell populations, cycle, apoptosis, and immune phenotypes.","Flow cytometer","Single-cell suspension"],
  "pcr":["PCR","PCR","Combine conventional PCR and RT-qPCR to verify target genes and expression.","PCR platform","DNA or RNA"],"wb":["Western Blot Validation","Western Blot","Validate protein abundance and phosphorylation pathways.","Electrophoresis and transfer system","Protein lysate"],"animal-model":["Run Animal Study","Animal Study","Build the model, randomize groups, dose, and collect whole-organism phenotypes.","Animal facility","Laboratory animals"],"clinical-monitor":["General-State Monitoring","Monitoring","Record weight, behavior, survival, and clinical signs.","Observation record","Animals or cases"],"biochem":["Blood / Tissue Biochemistry","Biochemistry","Measure liver, kidney, metabolic, and tissue-injury markers.","Clinical chemistry analyzer","Serum or tissue"],"he":["Histopathology","Histology","Prepare sections and use H&E or necessary special staining to observe tissue injury.","Pathology core","Fixed tissue"],"elisa":["ELISA / Cytokines","ELISA","Quantify inflammatory factors and secreted proteins.","Pathology assay core","Serum, tissue, or supernatant"],
  "genotoxicity":["Genotoxicity Battery","Genotoxicity","Use Ames, comet, or micronucleus assays to assess DNA damage.","Biosafety platform","Strains, cells, or marrow"],"lcms":["LC–MS/MS Toxicokinetics","LC–MS/MS","Quantify exposure, metabolites, and toxic windows.","Mass-spectrometry core","Plasma or tissue"],"organoid":["Organoid / 3D Model","Organoid","Validate 2D findings in a human-relevant three-dimensional model.","Organoid platform","Primary or iPSC-derived cells"],"transcriptomics":["RNA Sequencing","Transcriptomics","Generate quality-controlled global expression data; usable data may still be scientifically negative.","Sequencing core","High-quality RNA"],"proteomics":["Proteomics","Proteomics","Extract and quantify proteins to identify mechanism networks.","Mass-spectrometry core","Protein samples"],"metabolomics":["Metabolomics","Metabolomics","Profile metabolites and perturbed pathways.","Mass-spectrometry core","Serum, urine, or tissue"],"microbiome":["16S / Metagenomics","Microbiome","Resolve microbial composition and functional changes.","Sequencing core","Stool or environmental sample"],"single-cell":["Single-Cell Sequencing","Single Cell","Resolve cell states and heterogeneity from a high-viability suspension.","Single-cell platform","High-viability single cells"],"bioinformatics":["Omics Data Analysis","Omics Analysis","Perform QC, differential analysis, and pathway interpretation.","Workstation","Omics data"],"multiomics":["Multi-Omics Integration","Multi-Omics","Integrate multiple omics layers with phenotypes to build causal hypotheses.","Compute cluster","Multi-omics data"]
};
export function experimentText(experiment:ExperimentDefinition,locale:Locale){if(locale==="zh-CN")return experiment;const row=EXPERIMENT_EN[experiment.id];return row?{...experiment,name:row[0],short:row[1],description:row[2],equipment:row[3],sample:row[4]}:experiment;}

const ACTIVITY_EN:Record<ActivityId,[string,string]>={pilot:["Pilot Study","Test a small sample to optimize conditions and improve the next formal experiment."],literature:["Literature & Protocol","Strengthen theory and refine the experimental route."],analysis:["Data Analysis","Clean, analyze, and interpret existing results."],figure:["Make a Figure","Turn uncovered evidence into the next main figure."],writing:["Manuscript Writing","Advance the current paper and its scientific story."],review:["Respond to Reviewers","Answer each comment and connect it to revisions and new data."],thesis:["Graduate Thesis","Compile methods, results, and appendices late in year three."],grant:["Apply for Funding","Request flexible funds from the PI or department."],collaborate:["Collaborate","Trade expertise while potentially creating a social debt."],rest:["Proper Rest","Recover energy and SAN."],games:["Productive Slacking","Step away from research anxiety for a while."],date:["Date & Connection","Spend time with an eligible adult peer."],travel:["Short Trip","Use the full turn for a major recovery at the cost of progress."]};
export function activityText(id:ActivityId,value:{name:string;description:string},locale:Locale){if(locale==="zh-CN")return value;const row=ACTIVITY_EN[id];return row?{...value,name:row[0],description:row[1]}:value;}

const ENDING_EN:Record<string,[string,string,string]>={normal:["Graduated on Time","Graduation","After exactly three years, you leave with papers and the unmistakable scent of a laboratory."],excellent:["Graduated with Distinction","Graduation","The committee agrees that your evidence chain is complete."],late:["Graduated in Year Four","Graduation","The calendar turned a few extra pages, but the diploma arrived."],barely:["Graduated by a Hair","Graduation","The acceptance email arrived just before the system closed."],phd:["Continue to a PhD","Academic","You decide to keep pursuing the unanswered question."],"postdoc-star":["Rising Academic Star","Academic","High-quality work brings invitations from multiple teams."],"young-pi":["Exceptional Young PI","Academic","Years later, you lead your own group earlier than expected."],nobel:["A Future Nobel Clue","Academic","That unexpected finding eventually changes a field."],pharma:["Pharma R&D","Career","Your ability to diagnose failure enters the drug pipeline."],cro:["CRO Project Manager","Career","Scheduling, budgets, and communication become strengths."],platform:["Core Facility Scientist","Career","You can finally require everyone to book the instrument properly."],regulatory:["Pharmacovigilance & Regulatory","Career","Careful records become a professional moat."],love:["Graduation and Love","Life","Someone stays beside you through the final midnight sampling."],balanced:["Life Rebooted","Life","Research still matters, but no longer occupies the entire screen."],traveler:["On the Road","Life","You go to see a night sky without laboratory lights."],friendship:["The Lab Group Chat Forever","Life","Papers age; people who saved samples at 3 a.m. do not."],"lab-manager":["Laboratory Manager","Absurd","You know the temperament of every instrument."],coffee:["Guardian of the Coffee Machine","Absurd","The lab's most important infrastructure is now your responsibility."],reviewer:["Reviewer Survivor","Absurd","You review for editors and try not to become what you once hated."],"slack-master":["Master of Slacking","Absurd","You prove that recovery and work can form a stable oscillation."],withdraw:["Left Academia by Choice","Failure","Leaving is not failure; it is choosing another route."],burnout:["Burnout","Failure","Your body presses pause for you."],"integrity-fall":["Research Integrity Crisis","Failure","Beautiful results cannot cover missing records."],unfinished:["Still Unfinished in Year Four","Failure","The project continues, but this run ends here."]};
export function endingText(ending:EndingDefinition|undefined,locale:Locale){if(!ending||locale==="zh-CN")return ending;const row=ENDING_EN[ending.id];return row?{...ending,title:row[0],family:row[1] as EndingDefinition["family"],description:row[2]}:ending;}

const EVENT_SLUG_EN:Record<string,string>={freezer:"−80°C Freezer Alarm",antibody:"The Last Reliable Antibody",contam:"A Strange Cloud in the Incubator",machine:"Flow Cytometer Downtime",label:"Two Nearly Identical Sample Labels",power:"Nighttime Power Cut",reagent:"Reagent Batch Drift",animal:"Variable Animal Model",blind:"Blinded-Scoring Dispute",backup:"Workstation Drive Warning",platform:"A Sudden Core-Facility Opening",sample:"A Precious Sample for One Attempt",friday:"Friday, 5:58 p.m.","funding-cut":"Purchase Request Returned",praise:"Rare Praise from the PI",scope:"The Project Scope Expands Again",conference:"Conference Abstract Deadline",meeting:"Public Questions at Lab Meeting",holiday:"The PI Orders a Break","grant-deadline":"Emergency Grant Writing",authorship:"Authorship Negotiation","new-direction":"A Tempting New Direction",budget:"Year-End Budget Deadline",patience:"The PI Is Losing Patience",favor:"A Favor Comes Due","milk-tea":"Acceptance Milk Tea","stats-help":"Statistics Rescue Request",collab:"Cross-Lab Collaboration",graduation:"A Senior Student Clears the Bench",rumor:"Rumors of Being Scooped",conflict:"Shared-Freezer Dispute",credit:"Co-First Authorship Negotiation",meal:"Lunch Without Talking Science",farewell:"A Visiting Student Is Leaving","help-new":"A New Student Needs Help",network:"A Useful Conference Contact","date-conflict":"A Date Conflicts with Sampling",travel:"A Three-Day Trip",family:"Family Asks About Graduation",sleep:"Persistent Insomnia",exercise:"An Encounter at the Track",festival:"An Empty Holiday Laboratory",illness:"A Sudden Fever",concert:"A Concert Ticket",roommate:"A Roommate Moves Out",coffee:"The Coffee Machine Breaks",pet:"The Campus Cat's Feeding Time",career:"Industry Recruitment Talk",points:"Two Unattractive Data Points",duplicate:"A Possibly Duplicated Figure Panel",protocol:"Ethics Approval Does Not Cover the New Dose",selective:"Only Showing the Best Repeat","authorship-ethics":"A Gift-Authorship Proposal","raw-data":"Raw Data Without Timestamps",outlier:"Outlier-Handling Dispute","animal-welfare":"Animal-Welfare Concern",safety:"A Skipped Biosafety Step","scoop-ethics":"A Very Similar Preprint",negative:"Should Negative Results Be Hidden?",reuse:"Can Old Data Support a New Paper?"};
const CONFLICT_EVENT_EN:Record<string,[string,string]>={"conflict-extra-experiments":["‘Three More Experiments Will Complete the Story’","At the end of lab meeting, your PI circles three more gaps and gives you six turns."],"conflict-pickup-child":["The PI Asks You to Pick Up Their Child","A family emergency conflicts directly with your evening sampling."],"conflict-weekend-delivery":["Receive Reagents for the PI on Saturday","A cold-chain delivery conflicts with your prepaid trip."],"conflict-grant-pivot":["Your Project Is Redirected into a Grant","The PI wants two months of data for a proposal before you continue your thesis."],"conflict-authorship":["A Surprise Co-First Author","The PI wants to add someone who may contribute later."],"conflict-scoop":["A Labmate Presents Your Unpublished Idea","A slide at group meeting looks almost identical to your private plan."],"conflict-private-dinner":["Dinner with an Important Collaborator","The PI says attendance is ‘voluntary’ but clearly expects you there."],"conflict-vacation-samples":["Sample Duty During the Holiday","A senior student asks you to cover a week of time-sensitive samples."]};
const EVENT_CATEGORY_EN:Record<string,string>={"实验":"Lab","导师":"PI","人情":"Lab Politics","生活":"Life","伦理":"Ethics"};
const SPEAKER_EN:Record<string,string>={"导师":"PI","仪器室":"Instrument Room","值班群":"Duty Chat","科研秘书":"Research Administrator","内心审稿人":"Inner Reviewer","Figure 检查":"Figure Audit","伦理与统计专家":"Ethics and Statistics Expert","身体":"Your Body","家人":"Family","校园":"Campus","手机":"Phone","实验记录":"Lab Record","稿件草稿":"Manuscript Draft","文献预警":"Literature Alert"};
const GENERIC_EVENT_TEXT:Record<string,string>={"实验":"An unexpected technical problem forces you to choose between speed, cost, help, and rigor.","导师":"A new request from your PI conflicts with your current workload and boundaries.","人情":"A lab relationship now carries a real cost, favor, or authorship consequence.","生活":"Research collides with health, family, relationships, or the rest of your life.","伦理":"A tempting shortcut tests your records, transparency, and research integrity."};
export function eventText(event:EventNode,locale:Locale){if(locale==="zh-CN")return event;const conflict=CONFLICT_EVENT_EN[event.id];const slug=event.id.split("-").slice(1).join("-");return {...event,category:(EVENT_CATEGORY_EN[event.category]??event.category) as EventNode["category"],speaker:SPEAKER_EN[event.speaker]??(event.speaker==="导师"?"PI":"Lab colleague"),title:conflict?.[0]??EVENT_SLUG_EN[slug]??"Unexpected Research Event",text:conflict?.[1]??GENERIC_EVENT_TEXT[event.category]??"An unexpected event requires a decision."};}
const GENERIC_CHOICES:Record<string,Array<[string,string]>>={"实验":[["Stop and handle it properly","Energy ↓ · trust ↑"],["Ask the core staff for help","Funding ↓ · social skill ↑"],["Redesign around the anomaly","Theory ↑ · SAN ↓"],["Trust your luck","SAN ↑ · evidence risk"]],"导师":[["Discuss the workload directly","Trust ↑ · some pressure"],["Work overtime in silence","Energy ↓↓ · PI trust ↑"],["Negotiate with data and a timeline","Theory and social skill ↑"],["State that it cannot be done now","Keep energy · PI trust ↓"]],"人情":[["Help this time","Relationship ↑↑ · energy ↓"],["Propose a fair exchange","Relationship ↑ · clearer boundary"],["Coordinate a third person","Funding ↓ · social skill ↑"],["Decline clearly","Keep energy · relationship ↓"]],"生活":[["Make room for life","SAN ↑↑ · trust slightly ↓"],["Put the project first","Trust ↑ · SAN ↓"],["Trade shifts with a labmate","Relationship ↑ · favor debt"],["Delay the decision","Save time now · pressure ↑↑"]],"伦理":[["Follow the strictest standard","Integrity ↑↑ · slower progress"],["Consult an ethics or statistics expert","Funding ↓ · theory ↑"],["Keep full records and disclose limits","Writing ↑ · integrity ↑"],["Make the result look better first","Short-term trust ↑ · integrity ↓↓"]]};
const FLAG_CHOICE_EN:Record<string,[string,string]>={"accept-extra-experiments":["Accept the timed task","Finish three experiments in six turns for funding"],"negotiate-scope":["Negotiate with the evidence tree","Theory ↑ · pressure ↓"],"budget-before-work":["Demand funding first","Funding +¥18k · PI trust ↓"],"refuse-scope-creep":["Refuse endless scope creep","Keep energy · relationship falls"],"pickup-child":["Agree and reschedule sampling","Energy ↓ · PI trust ↑ · blurred boundary"],"delegate-private-task":["Ask a labmate to cover sampling","Relationship ↓ · favor-debt risk"],"professional-boundary":["Explain the experimental conflict","Social skill ↑ · outcome depends on PI"],"refuse-private-task":["Say you are unavailable","Keep time · PI trust ↓"],"weekend-duty":["Stay in the lab","Energy ↓↓ · trust ↑"],"paid-coordination":["Coordinate with a technician","Funding ↓ · social skill ↑"],"duty-roster":["Ask for a formal duty roster","Pressure ↑ · healthier future boundary"],"missed-delivery":["Take the trip anyway","SAN ↑ · cold-chain risk"],"grant-rescue":["Treat the grant as a collaboration","Funding ↑ · thesis delayed"],"grant-credit-agreed":["Define data use and credit first","Integrity ↑ · social skill ↑"],"limited-grant-help":["Provide existing results only","Keep energy · trust slightly ↓"],"refuse-grant-work":["Protect graduation progress","Pressure ↑ · PI trust ↓"]};
export function choiceText(choice:EventChoice,event:EventNode,index:number,locale:Locale){if(locale==="zh-CN")return choice;const row=choice.flag&&FLAG_CHOICE_EN[choice.flag]||GENERIC_CHOICES[event.category]?.[index]||["Choose this response","Consequences will follow"];return {...choice,label:row[0],hint:row[1]};}

const EXACT_EN:Record<string,string>={"湿实验":"Wet Lab","数据":"Data","写作":"Writing","理论":"Theory","社交":"Social","表型":"Phenotype","生化":"Biochemistry","病理":"Histology","分子":"Molecular","机制":"Mechanism","组学":"Omics","因果":"Causality","重复":"Replication","成功":"Success","技术失败":"Technical Failure","污染":"Contamination","清晰阳性":"Clear Positive","弱阳性":"Weak Positive","阴性":"Negative","矛盾":"Conflicting","意外发现":"Unexpected Discovery","经费充足":"Well Funded","实验完整性":"Evidence Completeness","严格":"Strict","宽松":"Relaxed","温和":"Supportive","中等":"Moderate","认真":"Attentive","失败":"Failure","毕业":"Graduation","学术":"Academic","就业":"Career","生活":"Life","荒诞":"Absurd"};
export function freeText(value:string,locale:Locale,fallback="Research update recorded."){
  if(locale==="zh-CN"||!value)return value;if(EXACT_EN[value])return EXACT_EN[value];
  let result=value.replace(/第\s*(\d+)\s*回合/g,"Turn $1").replace(/(\d+)\s*格/g,"$1 slots").replace(/(\d+)\s*项/g,"$1 items").replace(/(\d+)\s*组/g,"$1 sets");
  for(const [zh,en] of Object.entries(EXACT_EN))result=result.split(zh).join(en);
  return /[\u3400-\u9fff]/.test(result)?fallback:result;
}

export const STAT_EN={wet:"Wet Lab",data:"Data",writing:"Writing",theory:"Theory",social:"Social"} as const;
export const EVIDENCE_EN={phenotype:"Phenotype",biochemical:"Biochemistry",histology:"Histology",molecular:"Molecular",mechanism:"Mechanism",omics:"Omics",causality:"Causality",replication:"Replication"} as const;
export const SCOPE_EN:Record<string,string>={"食品":"Food","毒理":"Toxicology","机制":"Mechanism","药理":"Pharmacology","环境":"Environment","细胞":"Cell Biology","中药":"TCM","天然产物":"Natural Products","中医药":"Traditional Chinese Medicine","药学":"Pharmaceutical Science","转化":"Translational","污染物":"Pollutants","生态毒理":"Ecotoxicology","风险评价":"Risk Assessment","动物模型":"Animal Models","遗传毒性":"Genotoxicity","肿瘤":"Cancer","应用毒理":"Applied Toxicology","新药":"Drug Development","方剂":"Herbal Formulas"};
export const CHINESE_JOURNAL_EN:Record<string,string>={"中国药理学与毒理学杂志":"Chinese Journal of Pharmacology and Toxicology","中国药理学通报":"Chinese Pharmacological Bulletin","药学学报":"Acta Pharmaceutica Sinica","中国中药杂志":"China Journal of Chinese Materia Medica","中草药":"Chinese Traditional and Herbal Drugs","中国实验方剂学杂志":"Chinese Journal of Experimental Traditional Medical Formulae","中成药":"Chinese Traditional Patent Medicine","中国新药杂志":"Chinese Journal of New Drugs","中国药房":"China Pharmacy","中国现代应用药学":"Chinese Journal of Modern Applied Pharmacy","癌变·畸变·突变":"Carcinogenesis, Teratogenesis & Mutagenesis","中国比较医学杂志":"Chinese Journal of Comparative Medicine"};
export function journalProfile(language:"中文"|"英文",high:boolean,locale:Locale){if(locale==="zh-CN")return language==="中文"?"建议3–4张主图：核心表型、病理或生化、分子验证，并至少完成一次独立重复。":high?"建议5–6张主图：完整机制链、因果或挽救验证，并加入动物、类器官或组学加强证据。":"建议4–5张主图：表型—组织/生化—分子—机制链，并包含独立重复或交叉验证。";return language==="中文"?"Target 3–4 main figures: core phenotype, histology or biochemistry, molecular validation, and an independent repeat.":high?"Target 5–6 main figures: a complete mechanism chain, causal or rescue validation, plus stronger animal, organoid, or omics evidence.":"Target 4–5 main figures: phenotype, tissue/biochemistry, molecular validation, mechanism, and independent or orthogonal replication.";}
